# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  description: "↘️  This action will generate a un-opinionated changelog from conventional commits and suggest next tag version."
  topics: ivank, github-actions, typescript, conventional-commits, changelog, workflow
  homepage: https://github.com/workflow-actions/conventional-changelog-action.git
  private: false
  has_issues: true
  is_template: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
- name: main
