repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
    exclude: ^tsconfig.json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: ^dist/
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
  - id: mixed-line-ending
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character.
    # files: ^tests/
  - id: no-commit-to-branch
    args: [--branch, main, --branch, master]
  - id: pretty-format-json
    args: ['--autofix', '--indent=2']
    files: ^package.json
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: trailing-whitespace
    exclude: ^dist/
- repo: https://github.com/smian/pre-commit-makefile.git
  rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
  hooks:
  - id: makefile-doc
- repo: meta
  hooks:
  - id: check-useless-excludes
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
  - id: shellcheck
    exclude: ^.husky
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
  - id: markdownlint
    name: Markdownlint
    description: Run markdownlint on your Markdown files
    entry: mdl
    language: ruby
    files: \.(md|mdown|markdown)$
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.1
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    entry: 'yamllint --strict -d "{extends: relaxed, rules: {line-length: {max: 200}}}"'
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.3.0
  hooks:
  - id: prettier
    types: [javascript]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v4.1.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ["@commitlint/config-conventional"]
# local hooks
- repo: local
  hooks:
  - id: husky-run-pre-commit
    name: husky
    language: system
    entry: .husky/pre-commit
    pass_filenames: false
    always_run: false
    files: ^src/*|__tets__/*$
