# https://github.com/conventional-changelog/conventional-changelog/issues/670
branches:
  - master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      writerOpts:
        mainTemplate: |
          {{> header}}

          {{#if noteGroups}}
          {{#each noteGroups}}

          ### ⚠ {{title}}

          {{#each notes}}
          * {{#if commit.scope}}**{{commit.scope}}:** {{/if}}{{text}}
          {{/each}}
          {{/each}}
          {{/if}}
          {{#each commitGroups}}

          {{#if title}}
          ### {{title}}

          {{/if}}
          {{#each commits}}
          {{> commit root=@root}}
          {{/each}}

          {{/each}}

          {{> footer}}
        headerPartial: |
          {{#if isPatch~}}
          ###
          {{~else~}}
          ##
          {{~/if}} {{#if @root.linkCompare~}}
          [{{version}}]({{compareUrlFormat}})
          {{~else}}
          {{~version}}
          {{~/if}}
          {{~#if title}} "{{title}}"
          {{~/if}}
          {{~#if date}} ({{date}})
          {{/if}}
        commitPartial: |
          *{{#if scope}} **{{scope}}:**
          {{~/if}} {{#if subject}}
          {{~subject}}
          {{~else}}
          {{~header}}
          {{~/if}}

          {{~!-- commit link --}}{{~#if hash}} {{#if @root.linkReferences~}}
          ([{{shortHash}}]({{commitUrlFormat}}))
          {{~else}}
          {{~shortHash}}
          {{~/if}}{{~/if}}

          {{~!-- commit references --}}
          {{~#if references~}}
          , closes
          {{~#each references}} {{#if @root.linkReferences~}}
          [
          {{~#if this.owner}}
          {{~this.owner}}/
          {{~/if}}
          {{~this.repository}}{{this.prefix}}{{this.issue}}]({{issueUrlFormat}})
          {{~else}}
          {{~#if this.owner}}
          {{~this.owner}}/
          {{~/if}}
          {{~this.repository}}{{this.prefix}}{{this.issue}}
          {{~/if}}{{/each}}
          {{~/if}}
        footerPartial: |
          Thanks to all contributors!
  - - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogTitle: "# Changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): v${lastRelease.version} → v${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
