name: 01.build-test-run

on:
  workflow_dispatch:
  # rebuild any PRs and main branch changes
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - $default-branch
      - main
      - 'releases/*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build: # make sure we can build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get yarn cache
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        if: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache parcel
        uses: actions/cache@v2
        with:
          path: .parcel-cache
          key: ${{ runner.os }}-yarn

      - run: |
          yarn
          yarn test:coverage
          yarn build:parcel

      - name: run-action
        uses: ./
        id: run_action
        with:
          name: world

      - name: log-action-output
        run: echo ${{steps.run_action.outputs.gh_output}}
