# @todo: sync with other repositories
---
name: assign reviewers based on assignees

on:
  pull_request:
    types: [assigned, unassigned]
  pull_request_target:

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: assignee to reviewer
        uses: pullreminders/assignee-to-reviewer-action@v1.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
